sudo: false

language: rust
cache: cargo

os:
- linux
- osx

rust:
- nightly
- beta
- stable

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi

before_script:
- pip install -v 'travis-cargo<0.2' --user
- if [[ -e ~/Library/Python/2.7/bin ]]; then export PATH=~/Library/Python/2.7/bin:$PATH; fi
- if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi
- echo PATH is $PATH

script:
- |
  ([[ $TRAVIS_OS_NAME == "osx" ]] && (
      travis-cargo build -- --features signpost &&
      travis-cargo test -- --features signpost &&
      travis-cargo bench -- --features signpost
  ) || (
      travis-cargo build &&
      travis-cargo test  &&
      travis-cargo bench
  )) &&
  travis-cargo --only stable doc

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
